[package]
name = "lib_spells"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
bincode = "1.3.3"
bevy = { version = "0.13.1", default-features = false, features = ["serialize"] }
mio = { version = "0.8.11", features = ["os-poll", "net"] }
